apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-vet
  labels:
    app: clinic-vet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-vet
  template:
    metadata:
      labels:
        app: clinic-vet
    spec:
      containers:
      - name: clinic-vet
        image: clinicinsurancehealthrc.azurecr.io/clinic-vet:dev
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clinic-vet
spec:
  selector:
    app: clinic-vet
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer